- app.js
- config.js
- package-lock.json
- package.json
Added environment variables and config.js and made changes in app.js to listen to port from config. closes #2
> feat: Setup environment variables and config.js

- config.js
> Added staging environment at port 3001

- app.js
- config.js
- package-lock.json
- package.json
Created rate limiter with values read from .env file. closes #1
> Added Rate Limiter for Issue #1

- CONTRIBUTING.md
Added Labels section before Maintainers section on Contributing
> Docs: Added Labels Section

- public/css/common.css
- public/css/data-row.css
- views/components/data-row.ejs
Created data-row.ejs, and data-row.css, for the table row for the admin dashboard page. Also made changes to app.js to allow preview of the table data row for the admin dashboard page. View preview at /preview.
> Dashboard table row

- public/css/data-row.css
- public/css/table.css
- views/components/table.ejs
Added table.ejs, table.css. App.js displays table.ejs under the /preview route. Here are images for comparison
Original Design
table.ejs
cells auto-scale w/ table width. Feel free to make any changes/leave comments
> Dashboard Table w/ Brian's Table Rows

- app.js
- cache.js
- config.js
Added cache module and made it configurable to env and config.js
> feat: cache module

- public/js/dashboard.js
- views/components/data-row.ejs
- views/components/table.ejs
- views/temporary.ejs
From #32:  I got it working with made up id's for each row, which I think is a good solution because I'll I needed to do was add an id property to the data objects, which kind of simulates getting the id from the database. Also, I added a new js file "dashboard.js" because I assume we'll need more interactivity for the page later
> feat: added dashboard checkbox functionality

- package-lock.json
- package.json
- test/placeholder.spec.js
Installed the mocha and chai dependencies. Also added a test folder with a placeholder testing file.
> Set up testing framework

- public/js/dashboard.js
- views/components/data-row.ejs
- views/components/table.ejs
- views/temporary.ejs
added functionality for the header checkbox that selects/deselects all the rows in the table
> feat: added header checkbox functionality

- public/css/common.css
some of the css can be combined with the item highlighting code
> feat: navbar "become a member" button animation

- app.js
- public/css/login.css
- views/login.ejs
Displays login error instead of redirecting to /auth/login. Closes #53
> Login error

- public/css/common.css
fixes footer overlapping other page content
> fix: made footer position static

- public/css/common.css
> fix: body width now 100% of display width

- public/css/admin.css
- public/css/common.css
- views/admin.ejs
- views/components/footer.ejs
fixes overflow issue on index and added some padding to footer
> fix: landing page style tweaks

- views/admin.ejs
- views/components/images-table.ejs
Created images table in the admin dashboard page based on the previous blog and user tables. Only made changes to `admin.ejs` and added `images-table.ejs`. No changes to styling were made. Checkboxes function same as other tables and do not appear to affect other tables.
> Added images table to admin.ejs based on previous tables

- views/components/navbar.ejs
- views/index.ejs
> feat: added in-page anchors for navbar

- app.js
- views/admin.ejs
- views/components/users-table.ejs
> feat: populate users table with data from db

- routes/api.js
- routes/blog.js
Created routes for blog. closes issue #69
> Blog route

- public/css/index.css
- views/index.ejs
Made the about box responsive. Removed some `div` containers in index.ejs to turn the `about__get-started` section into a CSS grid. Added a media query at the end of index.css. Also removed `.about` selector in index.css to fix section spacing.
> Made 'about box' responsive

- public/css/index.css
- public/js/index.js
I have fixed the problem with the porfolio section that wasn't scrolling correctly in smaller screens.
I have commented all the changes in the code for you to understand why those changes and how does the code work.
If you have any question or want to ask me something, don't hesitate to do it!
> fixed issue #95 - porfolio section fixed

- public/css/common.css
- public/css/index.css
- views/index.ejs
Wrote the form, still having issues with the line placement and haven't added the text space. Submit button also hasn't been styled
> Created the form

- routes/blog.js
- views/article.ejs
> issue #88 done

- config.js
- public/js/index.js
- routes/api.js
- routes/contact.js
- views/index.ejs
Filling and submitting the contact form now sends an email (via SMTP relay) to the UF admin email address and the original form sender.
> feat: Contact form

- views/components/users-table.ejs
> fix: users table checkbox bug

- public/css/admin.css
- public/js/dashboard.js
- views/admin.ejs
- views/components/blog-table.ejs
- views/components/images-table.ejs
- views/components/users-table.ejs
closes https://github.com/ufosc/Club_Website_2/issues/87
**Done**: I have Implemented the delete button as described in issue https://github.com/ufosc/Club_Website_2/issues/87.
I have implemented a function ```deleteButtonVisiblity()``` which checks if any of the check box is checked (or marked) , then it makes the delete-button visible .If none of the check box in the table is checked (or marked) ,then it makes the delete-button invisible.
> Implemented the delete button in views/admin.ejs 

- public/css/index.css
- views/components/navbar.ejs
- Fixed about navlink
- Smooth Scrolling feature added
> Fix #199, about navlink

- public/css/admin.css
- public/css/edit.css
- public/js/dashboard.js
- public/js/editDb.js
- routes/api.js
- routes/blog.js
- routes/edit.js
- routes/users.js
- utils/seed.js
- views/admin.ejs
- views/components/blog-table.ejs
- views/components/navbar.ejs
- views/components/users-table.ejs
- views/edit-blog.ejs
- views/edit-user.ejs
Allows admins to edit users and blog entries.
> Edit entries

- public/js/dashboard.js
- views/admin.ejs
> feat: implemented admin delete button

- package-lock.json
- public/css/common.css
I have resolved the font issue , their was a mistake in path which is now resolved.
> path correction in common.css

- public/css/blog.css
- public/css/common.css
- public/css/index.css
- public/js/dotmap.js
- views/blog.ejs
- views/index.ejs
Fixes mobile responsiveness on index.ejs by positioning and resizing the animation through javascript.
> fix: index.ejs responsiveness

- views/article.ejs
Article 'Date' not formatting correctly, changed it to the required format.
> fixed article date format

- .gitignore
- app.js
- model/images.js
- package-lock.json
- package.json
- public/js/dashboard.js
- public/js/editDb.js
- routes/api.js
- routes/blog.js
- routes/edit.js
- routes/images.js
- views/admin.ejs
- views/components/images-table.ejs
- views/components/navbar.ejs
- views/edit-image.ejs
> feat: Images route

- package.json
- test/edit.spec.js
- utils/config.js
> Test edit route

- public/css/common.css
> issue #168 <updated app>(<css>):<add margin for alert> <BREAKING CHANGE: Closes 

- views/blog.ejs
Hello. I have added navbar in the blog.ejs in Views as you suggested. Fixes: #173
> bug: added navbar in blog.ejs

- package-lock.json
- public/js/index.js
Closes #189 
Resets form fields and recaptcha token on a successful submission
> tweak: contact form

- app.js
- public/css/common.css
- utils/callbacks.js
- views/components/blog-grid.ejs
- views/components/footer.ejs
- views/index.ejs
* Added lazy-loading
* Critical CSS files are loaded inline via EJS.
* Fixed compression issue
* Defer animation
> Load optimize

- app.js
- package.json
- utils/cache.js
- utils/config.js
- utils/database.js
Index page is blank on cold starts because the page gets served before index can be rendered.
> Fix cold start

- src/content/2024-10-08-where-is-cse101.md
- src/content/2024-10-08.md
> blog: where is CSE A101?
